package com.eshop.webmvc.config;

import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import org.springframework.security.oauth2.client.web.AuthorizationRequestRepository;
import org.springframework.security.oauth2.core.endpoint.OAuth2AuthorizationRequest;
import org.springframework.security.oauth2.core.endpoint.OAuth2ParameterNames;
import org.springframework.util.StringUtils;

import java.util.concurrent.ConcurrentHashMap;

/**
 * Stores OAuth2 authorization requests in a server-side ConcurrentHashMap keyed by the
 * OAuth2 state parameter. This sidesteps the session-cookie and cross-port cookie issues
 * that arise in Docker dev environments where the browser navigates between
 * host.docker.internal:5100 (webmvc) and host.docker.internal:5105 (Keycloak).
 *
 * Security: the state value is a cryptographically random 256-bit token generated by
 * Spring Security, so it serves as CSRF protection. Entries are removed after use.
 */
public class StateKeyedOAuth2AuthorizationRequestRepository
        implements AuthorizationRequestRepository<OAuth2AuthorizationRequest> {

    private final ConcurrentHashMap<String, OAuth2AuthorizationRequest> store = new ConcurrentHashMap<>();

    @Override
    public OAuth2AuthorizationRequest loadAuthorizationRequest(HttpServletRequest request) {
        String state = request.getParameter(OAuth2ParameterNames.STATE);
        if (!StringUtils.hasText(state)) {
            return null;
        }
        return store.get(state);
    }

    @Override
    public void saveAuthorizationRequest(OAuth2AuthorizationRequest authorizationRequest,
                                         HttpServletRequest request, HttpServletResponse response) {
        if (authorizationRequest == null) {
            String state = request.getParameter(OAuth2ParameterNames.STATE);
            if (StringUtils.hasText(state)) {
                store.remove(state);
            }
            return;
        }
        if (store.size() >= 200) {
            store.clear();
        }
        store.put(authorizationRequest.getState(), authorizationRequest);
    }

    @Override
    public OAuth2AuthorizationRequest removeAuthorizationRequest(
            HttpServletRequest request, HttpServletResponse response) {
        String state = request.getParameter(OAuth2ParameterNames.STATE);
        if (!StringUtils.hasText(state)) {
            return null;
        }
        return store.remove(state);
    }
}
