server:
  port: 5114

spring:
  application:
    name: webhookclient
  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: HTML
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: webhooksclient
            client-secret: secret
            authorization-grant-type: authorization_code
            scope: openid,profile,webhooks
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          keycloak:
            issuer-uri: http://localhost:5105/realms/eshop
            user-name-attribute: preferred_username

services:
  webhooks-url: http://webhooks-api:5113

webhook-client:
  token: "secret-token"
  callback-url: "http://webhookclient:5114/webhook/receive"

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: health,info
      path-mapping:
        health: hc
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
